### ISSUE TITLE
Launch review from KB

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#126]
In the Appendix (About the Essential Guide):
- [x] under What’s Changed, I believe #5 should say “nation-state” not “national state”—ie. “The nature of threats has changed. In 2016, nation-state actors posed most of the apparent risks.”  
- [x] And maybe actually we should instead say “foreign adversaries” rather than nation-state actors? 

Under How is this version different, #1, a few typos.  
- [x] The sentence starting with “This roughly said” needs to delete the duplicative “what”  (should say “This roughly said in what order to do things”)
- [x] Also in same paragraph, addresses is missing a “d”  “For any best practice, the approach to implementation addresses whether….”

On the Maturities page,
- [x] On Level 2 description, there’s an extra “in” near the end after “within” that should be deleted.
- [x] Should Level 3 say risks instead of risk?: “The organization assesses its risks….”

- [x] On the Level 1 Worksheet page, I’m assuming you will delete the “Soft Launch Draft” box at the top.  
- [x] Also, I don’t see links to actual worksheets on this page, but I’m assuming they’re just not there yet? :)

- [x] On the Encrypt Data at rest page, I’m assuming you will delete the “Soft Launch Draft” box at the top.  (this is obviously on many pages so I will stop noting this and assume you know this)

- [x] I feel like the “Maturity Alignment to Best Practices” page is hard to understand for non-techies. Even the title of the page is hard to understand.  Can we call it Next Steps for Best Practices or something like that?  
- [x] Also in the first sentence at the top can we change the description to something like: “This section provides baseline goals for each maturity level and links to best practices that apply for each.”
- [x] The Chart in the middle of the Level 1 section is confusing. For example- Will the items listed in the “Worksheet” column have links to actual worksheets? If one of the main goals is to get people to print out those worksheets, that should be a wider and more prominent column, and the best practice column should be smaller or the same width/prominence.
- [x] What does “Actions Covered” mean and refer to?  What are the #1 and #2 and “all” etc. listed in the rows of that column referring to?
- [x] In the paragraph right under the big chart/box, it should say “suggestion” not “A suggestions:”
- [x] Under Level 1 Maturity Election Priorities section, #5, should be a verb before “A removable media sanitization program.”   Implement? Create?
- [x] Under Level 2 & 3 CDM paragraph, the first sentence has typos and should be changed to” To help answer questions as to where cybersecurity practioners should invest their next dollar….”
- [x] Also in the CDM section, about 5 paragraphs down, the sentence beginning with “The goal” has a typo- should say “which” instead of with.  “The goal of the CDM is to determine which mitigations…”

- [x] On the “Encrypt Data at Rest” page, the Level 1 guidance will not be understandable for most Level 1 election officials.  It says “Enable full disk encryption on all devices that have encryption technologies built into the device.”  They will not have any clue what this means or how to do this.  Can this be simplified and explained/walked through in easier terms?  
- [x] Also the initial explanatory paragraphs could use more simple description.

- [x] Similar request for the “Managing Infrastructure” page. I think it assumes more understanding than laypeople will have in both the initial explanatory paragraphs as well as the Level 1 guidance.  Can this be simplified and walked through in easier terms?
