### ISSUE TITLE
Launch review from KB, part 2

### ISSUE THREAD

**Issue by mike-garcia** [it-dept-cis/Essential-Guide-to-Election-Security#132]
continues #126 

On the User Management page, the Level 1 section also needs to be simplified and explained/walked through in easier terms, sorry.  A few specific notes on this page:
- [x] I would edit the “To reduce this risk” sentence to this:  “To reduce your risk, you need to not only implement strong protections on every user account, but also build in limitations on the damage that may be caused by a breach of a single user account.”
- [x] On the Passwords bullet, it’s missing an “a” before “common vector.”
- [ ] Can you delete “level 1 maturity” next to all the bullets under Goals?  I think all those goals also apply to all maturities.
- [x] Salting and Hashing are not defined nor described- they’re in Goals and Level 1 recommendations – and will not be known/understood by level 1 people.
- [x] Under User Recommendations, for #3, can you edit to this?:  “One way to create the strongest passwords is to use passphrases, ideally of at least four words of 5+ letters, instead of random sets of characters. If you do this, you don’t need to use composition rules like upper, lower, number, and symbols.  An example of a very strong passphrase password would be [INSERT EXAMPLE].”
- [x] Can we give more information about what MFA is, or at least add a sentence explaining and maybe link to an online resource explaining examples?  I know it’s hard to believe but there are still a lot of laypeople who have no idea what MFA is, and the glossary just says multifactor authentication without explaining.
- [x] Under Organizational recommendation #2, it says “This is especially true for anything accessed offsite or from offsite….” Is that a typo, or what is meant by listing both?
- [ ] Maybe at the top of the Organizational recommendation you can say “Ask your IT provider or administrator whether you have the following in place, and if not, implement these actions:”
- [x] Level 1 people also won’t know what reversible encryption is or where to find it.
- [x] For #4 under organizational recommendations, is there a typo in this clause?  “…and require at least 15 minutes between account lockout.”  I don’t understand what this clause is recommending.
- [x] Under #6, can you edit the 2nd and 3rd sentences to say this instead:  “This limits the damage that may be caused by a breach of any single account. This is particularly important for any account with administrative access to sensitive network controls and/or confidential materials.”

§  Can you edit #7 & 8 as shown below?
- [x] #7: “Review levels of individuals’ access regularly and revoke any unnecessary or inappropriate access. Establish a plan to do this regularly, and make it part of the offboarding and job change processes to ensure that user has access to what they need and nothing else.”
- [x]   #8: “Employ user logging on your networks. You should be able to see whenever a user logs into a device or network, and maintain records of these logs.”

**Comment by mike-garcia** [comment]
- [ ] On the Backups page, a “be” is missing from this sentence – should say  “Backup programs should BE developed based on six characteristics:”
- [ ] Under Level 1 maturity, the sentence is missing an end.  It says “Creating a data inventory for a Level 1 maturity organization should I”
- [ ] The Incident Response page seems to contain the wrong content.  I think it contains the User Management page content instead.

Building and Managing Staff page
- [ ] For the second paragraph on the top section, can you please edit the last 2 sentences to “In addition, carefully manage staff access, both physical and electronic, and provide them the training they need so they can make good cybersecurity decisions.”
- [ ] Under goals, can you delete the (level 1 maturity) parentheticals after each goal?  (apply to all maturities)
